INSERT INTO song VALUES(1,"Montania", "Calma Interiore");
INSERT INTO song VALUES(2,"Amoralis", "Sheila's Disciples");
INSERT INTO song VALUES(3,"Objective", "Olivier Lupin");
INSERT INTO song VALUES(4,"Glemt Perle", "Aksel Møller");
INSERT INTO song VALUES(5,"Liberation", "Nova Issue");
INSERT INTO song VALUES(6,"Inner Peace", "Sabrina McGregor");
INSERT INTO song VALUES(7,"Lorimor", "Savasana");
INSERT INTO song VALUES(8,"Silk", "Sleepwear");
INSERT INTO song VALUES(9,"Flucht", "Elias Dome");
INSERT INTO song VALUES(10,"This Now", "Nela Bautista");
INSERT INTO song VALUES(11,"At the Gate", "Insomnia Curator");
INSERT INTO song VALUES(12,"Lagoons", "Xiada");
INSERT INTO song VALUES(13,"Tirana Wolves", "Wolves Club");
INSERT INTO song VALUES(14,"Choices", "Alva Adler");
INSERT INTO song VALUES(15,"Selama Aku Bersamamu", "Indah Bethari");
INSERT INTO song VALUES(16,"Bid to Wonder", "Reinstallation Conundrum");
INSERT INTO song VALUES(17,"Dusk Sermons", "Le Palade");
INSERT INTO song VALUES(18,"Een mooie droom", "Zeb Maessen");
INSERT INTO song VALUES(19,"A côté de toi", "Delit Quirion");
INSERT INTO song VALUES(20,"Aurora Borealis", "Astro.Not");
INSERT INTO album VALUES(1, "Montania", "Calma Interiore", "2021-09-27");
INSERT INTO album VALUES(2, "Always Wear A Crown", "Sheila's Disciples", "2021-09-24");
INSERT INTO album VALUES(3, "Objective", "Olivier Lupin", "2021-08-30");
INSERT INTO album VALUES(4, "Glemt Perle", "Aksel Møller", "2022-02-28");
INSERT INTO album VALUES(5, "Liberation", "Nova Issue", "2021-05-25");
INSERT INTO album VALUES(6, "Inner Peace", "Sabrina McGregor", "2022-01-26");
INSERT INTO album VALUES(7, "Lorimor", "Savasana", "2021-03-11");
INSERT INTO album VALUES(8, "Contemplate", "Sleepwear", "2022-02-07");
INSERT INTO album VALUES(9, "Flucht", "Elias Dome", "2022-01-27");
INSERT INTO album VALUES(10, "This Now", "Nela Bautista", "2022-02-24");
INSERT INTO album VALUES(11, "Entering Dreamland", "Insomnia Curator", "2021-08-24");
INSERT INTO album VALUES(12, "Lagoons", "Xiada", "2022-03-04");
INSERT INTO album VALUES(13, "On the Davenport", "Wolves Club", "2020-10-12");
INSERT INTO album VALUES(14, "Choices", "Alva Adler", "2022-01-24");
INSERT INTO album VALUES(15, "Selama Aku Bersamamu", "Indah Bethari", "2022-02-22");
INSERT INTO album VALUES(16, "Sochi", "Reinstallation Conundrum", "2021-09-19");
INSERT INTO album VALUES(17, "Dusk Sermons", "Le Palade", "2022-02-17");
INSERT INTO album VALUES(18, "Een mooie droom", "Zeb Maessen", "2022-02-18");
INSERT INTO album VALUES(19, "A côté de toi", "Delit Quirion", "2022-02-11");
INSERT INTO album VALUES(20, "Aurora Borealis", "Astro.Not", "2022-01-31");
INSERT INTO in_album VALUES(1, 1);
INSERT INTO in_album VALUES(2, 2);
INSERT INTO in_album VALUES(3, 3);
INSERT INTO in_album VALUES(4, 4);
INSERT INTO in_album VALUES(5, 5);
INSERT INTO in_album VALUES(6, 6);
INSERT INTO in_album VALUES(7, 7);
INSERT INTO in_album VALUES(8, 8);
INSERT INTO in_album VALUES(9, 9);
INSERT INTO in_album VALUES(10, 10);
INSERT INTO in_album VALUES(11, 11);
INSERT INTO in_album VALUES(12, 12);
INSERT INTO in_album VALUES(13, 13);
INSERT INTO in_album VALUES(14, 14);
INSERT INTO in_album VALUES(15, 15);
INSERT INTO in_album VALUES(16, 16);
INSERT INTO in_album VALUES(17, 17);
INSERT INTO in_album VALUES(18, 18);
INSERT INTO in_album VALUES(19, 19);
INSERT INTO in_album VALUES(20, 20);
